export const footerLinks = [
  {
    title: "About",
    links: [
      { title: "How it works", url: "/" },
      { title: "Featured", url: "/" },
      { title: "Partnership", url: "/" },
      { title: "Bussiness Relation", url: "/" },
    ],
  },
  {
    title: "Company",
    links: [
      { title: "Events", url: "/" },
      { title: "Blog", url: "/" },
      { title: "Podcast", url: "/" },
      { title: "Invite a friend", url: "/" },
    ],
  },
  {
    title: "Socials",
    links: [
      { title: "Discord", url: "/" },
      { title: "Instagram", url: "/" },
      { title: "Twitter", url: "/" },
      { title: "Facebook", url: "/" },
    ],
  },
];

// I got these cars from ChatGPT 😊
export const manufacturers = [
  "Toyota",
  "Volkswagen",
  "Audi",
  "Porsche",
  "Lamborghini",
  "Bentley",
  "Chevrolet",
  "GMC",
  "Buick",
  "Cadillac",
  "Ford",
  "Lincoln",
  "BMW",
  "Mini",
  "Rolls",
  "Royce",
  "Mercedes Benz",
  "Smart",
  "Honda",
  "Nissan",
  "Hyundai",
  "Kia",
  "Genesis",
  "Fiat",
  "Chrysler",
  "Jeep",
  "Dodge",
  "Ram",
  "Subaru",
  "Mazda",
  "Mitsubishi",
  "Volvo",
  "Tesla",
  "Jaguar",
  "Land Rover",
  "Peugeot",
  "Citroën",
  "DS",
  "Opel",
  "Vauxhall",
  "Renault",
  "Dacia",
  "Alpine",
  "Suzuki",
  "Aston Martin",
  "Ferrari",
  "McLaren Automotive",
  "Bugatti",
  "Alfa Romeo",
  "Lotus Cars",
  "BYD Auto",
  "Geely",
  "MG",
  "Roewe",
  "Great Wall",
  "Chery",
];

export const yearsOfProduction = [
  { title: "Year", value: "" },
  { title: "2015", value: "2015" },
  { title: "2016", value: "2016" },
  { title: "2017", value: "2017" },
  { title: "2018", value: "2018" },
  { title: "2019", value: "2019" },
  { title: "2020", value: "2020" },
  { title: "2021", value: "2021" },
  { title: "2022", value: "2022" },
  { title: "2023", value: "2023" },
];

export const fuels = [
  {
    title: "Fuel",
    value: "",
  },
  {
    title: "Gas",
    value: "Gas",
  },
  {
    title: "Electricity",
    value: "Electricity",
  },
];
